// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsStaging{
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVXcml6j-piRS0_vgH04ASZHlcv75E2yo',
    appId: '1:457407377680:web:08b06204933da17ab57595',
    messagingSenderId: '457407377680',
    projectId: 'hotel-app-dev-69159',
    authDomain: 'hotel-app-dev-69159.firebaseapp.com',
    storageBucket: 'hotel-app-dev-69159.appspot.com',
    measurementId: 'G-1CZW2GXJ6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vhFKGZ-MxlAvm8HIfX2Waob6gbKKJec',
    appId: '1:457407377680:android:39f6714f0189d361b57595',
    messagingSenderId: '457407377680',
    projectId: 'hotel-app-dev-69159',
    storageBucket: 'hotel-app-dev-69159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDZcXwB_GTIAec0BfFWr2WuWU2OtVjvs',
    appId: '1:457407377680:ios:fee72ab1b23e37e1b57595',
    messagingSenderId: '457407377680',
    projectId: 'hotel-app-dev-69159',
    storageBucket: 'hotel-app-dev-69159.appspot.com',
    iosBundleId: 'vn.dhysolutions.hotel-spa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDZcXwB_GTIAec0BfFWr2WuWU2OtVjvs',
    appId: '1:457407377680:ios:da60cde6876892f3b57595',
    messagingSenderId: '457407377680',
    projectId: 'hotel-app-dev-69159',
    storageBucket: 'hotel-app-dev-69159.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
