// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsProduct {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ubxJ8iN2FyYTSCXbyDJ-CXPC5v54VCE',
    appId: '1:922903032667:web:8c7781392fee4f68a4a07e',
    messagingSenderId: '922903032667',
    projectId: 'hotel-app-product',
    authDomain: 'hotel-app-product.firebaseapp.com',
    storageBucket: 'hotel-app-product.appspot.com',
    measurementId: 'G-CD3QFR36EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhxNBsayL0WvHEJ8JLH2Jbzbun61T2XFU',
    appId: '1:922903032667:android:379795ad54dd0e99a4a07e',
    messagingSenderId: '922903032667',
    projectId: 'hotel-app-product',
    storageBucket: 'hotel-app-product.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnzHLRLivzrabTo7t6FIY2xA5OIo5NOGM',
    appId: '1:922903032667:ios:6061643daa6dbd5ba4a07e',
    messagingSenderId: '922903032667',
    projectId: 'hotel-app-product',
    storageBucket: 'hotel-app-product.appspot.com',
    iosBundleId: 'vn.dhysolutions.hotel-spa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnzHLRLivzrabTo7t6FIY2xA5OIo5NOGM',
    appId: '1:922903032667:ios:e2cb70a72d7eb297a4a07e',
    messagingSenderId: '922903032667',
    projectId: 'hotel-app-product',
    storageBucket: 'hotel-app-product.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
